# Generated by Django 5.2.17 on 2026-09-24 15:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=80, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[0-9+() -]+$', 'Введите корректный номер телефона.')], verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='ads.advertisement', verbose_name='Рекламная кампания')),
            ],
            options={
                'verbose_name': 'потенциальный клиент',
                'verbose_name_plural': 'потенциальные клиенты',
                'ordering': ('last_name', 'first_name'),
            },
        ),
    ]
