# Generated by Django 5.2.17 on 2026-09-24 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('document', models.FileField(blank=True, upload_to='contracts/', verbose_name='Файл договора')),
                ('start_date', models.DateField(verbose_name='Дата заключения')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='products.product', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'контракт',
                'verbose_name_plural': 'контракты',
                'ordering': ('-start_date',),
            },
        ),
    ]
